//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfilesOnTopReplica {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProfilesOnTopReplica.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Created by: %. ähnelt.
        /// </summary>
        internal static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lorenz Cuno Klopfenstein ähnelt.
        /// </summary>
        internal static string AboutAuthorContent {
            get {
                return ResourceManager.GetString("AboutAuthorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort update process. ähnelt.
        /// </summary>
        internal static string AboutButtonCancelTT {
            get {
                return ResourceManager.GetString("AboutButtonCancelTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show details about OnTopReplica. ähnelt.
        /// </summary>
        internal static string AboutButtonExpanderTT {
            get {
                return ResourceManager.GetString("AboutButtonExpanderTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset all OnTopReplica settings. ähnelt.
        /// </summary>
        internal static string AboutButtonResetTT {
            get {
                return ResourceManager.GetString("AboutButtonResetTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update OnTopReplica now. ähnelt.
        /// </summary>
        internal static string AboutButtonUpdateTT {
            get {
                return ResourceManager.GetString("AboutButtonUpdateTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Care to contribute to the project? You are welcome to improve available translations, start a new one for your native language or to check out the % from CodePlex. ähnelt.
        /// </summary>
        internal static string AboutContribute {
            get {
                return ResourceManager.GetString("AboutContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die source code ähnelt.
        /// </summary>
        internal static string AboutContributeContent {
            get {
                return ResourceManager.GetString("AboutContributeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica is based upon the WindowsFormsAero library and some other libraries and code sources. %. ähnelt.
        /// </summary>
        internal static string AboutCreditsSources {
            get {
                return ResourceManager.GetString("AboutCreditsSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read the full credits ähnelt.
        /// </summary>
        internal static string AboutCreditsSourcesContent {
            get {
                return ResourceManager.GetString("AboutCreditsSourcesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contribute ähnelt.
        /// </summary>
        internal static string AboutDividerContribute {
            get {
                return ResourceManager.GetString("AboutDividerContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        internal static string AboutDividerCredits {
            get {
                return ResourceManager.GetString("AboutDividerCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        internal static string AboutDividerLicense {
            get {
                return ResourceManager.GetString("AboutDividerLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updates ähnelt.
        /// </summary>
        internal static string AboutDividerUpdates {
            get {
                return ResourceManager.GetString("AboutDividerUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The application is licensed under the % license, which meets the terms of the &quot;open-source&quot; definition specified by OSI. ähnelt.
        /// </summary>
        internal static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Reciprocal (MS-RL) ähnelt.
        /// </summary>
        internal static string AboutLicenseContent {
            get {
                return ResourceManager.GetString("AboutLicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A lightweight, real-time, always on top thumbnail of a window of your choice. ähnelt.
        /// </summary>
        internal static string AboutSlogan {
            get {
                return ResourceManager.GetString("AboutSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About OnTopReplica ähnelt.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translators: {0} ähnelt.
        /// </summary>
        internal static string AboutTranslators {
            get {
                return ResourceManager.GetString("AboutTranslators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Christian Olaechea M., Daniel Zeus.EX, Federico Lorenzo, Goran Brecelj, Jan Romanczyk, Marco Kraxner, Patrik (batupata), Raúl Morillo, René Mihula, Roberto Leiro, Rodrigo Lourenço, Thomas Amundsen, Eric Hoffmann. ähnelt.
        /// </summary>
        internal static string AboutTranslatorsContent {
            get {
                return ResourceManager.GetString("AboutTranslatorsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check now! ähnelt.
        /// </summary>
        internal static string AboutUpdatesCheckNow {
            get {
                return ResourceManager.GetString("AboutUpdatesCheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica automatically checks for updates at every start up. ähnelt.
        /// </summary>
        internal static string AboutUpdatesDisclaimer {
            get {
                return ResourceManager.GetString("AboutUpdatesDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} ähnelt.
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica ähnelt.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset window completely? ähnelt.
        /// </summary>
        internal static string AskReset {
            get {
                return ResourceManager.GetString("AskReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Reset
        ///All settings will be lost. ähnelt.
        /// </summary>
        internal static string AskResetButtonOk {
            get {
                return ResourceManager.GetString("AskResetButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can be used to reset all settings if you lost control over the window or moved it beyond the screen boundary. ähnelt.
        /// </summary>
        internal static string AskResetContent {
            get {
                return ResourceManager.GetString("AskResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string AskResetTitle {
            get {
                return ResourceManager.GetString("AskResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset settings? ähnelt.
        /// </summary>
        internal static string AskSettingReset {
            get {
                return ResourceManager.GetString("AskSettingReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This will erase all settings of OnTopReplica, returning it to the original state right after installation (all saved information, like stored regions, will be lost). ähnelt.
        /// </summary>
        internal static string AskSettingResetContent {
            get {
                return ResourceManager.GetString("AskSettingResetContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset settings ähnelt.
        /// </summary>
        internal static string AskSettingResetTitle {
            get {
                return ResourceManager.GetString("AskSettingResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw regions using mouse. ähnelt.
        /// </summary>
        internal static string DrawRegions {
            get {
                return ResourceManager.GetString("DrawRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        internal static string ErrorDetailButton {
            get {
                return ResourceManager.GetString("ErrorDetailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details on Windows Aero ähnelt.
        /// </summary>
        internal static string ErrorDetailsAero {
            get {
                return ResourceManager.GetString("ErrorDetailsAero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Aero is only available on Windows Vista Home Premium or higher. ähnelt.
        /// </summary>
        internal static string ErrorDetailsAeroInfo {
            get {
                return ResourceManager.GetString("ErrorDetailsAeroInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;Desktop Composition&apos; is not enabled. ähnelt.
        /// </summary>
        internal static string ErrorDwmOff {
            get {
                return ResourceManager.GetString("ErrorDwmOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You must enable desktop composition, by selecting &apos;Windows Aero&apos; as the theme used by Windows.
        ///
        ///To do so, right-click on the desktop and click on Personalize. ähnelt.
        /// </summary>
        internal static string ErrorDwmOffContent {
            get {
                return ResourceManager.GetString("ErrorDwmOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error details ähnelt.
        /// </summary>
        internal static string ErrorGenericInfoButton {
            get {
                return ResourceManager.GetString("ErrorGenericInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error:  ähnelt.
        /// </summary>
        internal static string ErrorGenericInfoText {
            get {
                return ResourceManager.GetString("ErrorGenericInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It appears that the selected window has been closed or is not valid anymore. ähnelt.
        /// </summary>
        internal static string ErrorGenericThumbnailHandleError {
            get {
                return ResourceManager.GetString("ErrorGenericThumbnailHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ErrorGenericTitle {
            get {
                return ResourceManager.GetString("ErrorGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desktop Composition&apos; is not supported on your Operating System.
        ///You must run this application on Windows Vista Home Premium or better. ähnelt.
        /// </summary>
        internal static string ErrorNoDwm {
            get {
                return ResourceManager.GetString("ErrorNoDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Desktop Composition unsupported ähnelt.
        /// </summary>
        internal static string ErrorNoDwmTitle {
            get {
                return ResourceManager.GetString("ErrorNoDwmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No thumbnail loaded. ähnelt.
        /// </summary>
        internal static string ErrorNoThumbnail {
            get {
                return ResourceManager.GetString("ErrorNoThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to create thumbnail ähnelt.
        /// </summary>
        internal static string ErrorUnableToCreateThumbnail {
            get {
                return ResourceManager.GetString("ErrorUnableToCreateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to fit window. ähnelt.
        /// </summary>
        internal static string ErrorUnableToFit {
            get {
                return ResourceManager.GetString("ErrorUnableToFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to check for updates. ähnelt.
        /// </summary>
        internal static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It appears that OnTopReplica wasn&apos;t installed using &apos;ClickOnce&apos;. You&apos;ll have to update manually (visit &lt;a href=&quot;http://ontopreplica.codeplex.com&quot;&gt;OnTopReplica&apos;s homepage&lt;/a&gt;). ähnelt.
        /// </summary>
        internal static string ErrorUpdateContent {
            get {
                return ResourceManager.GetString("ErrorUpdateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica was unable to check whether an updated version is available. Make sure you are connected to the Internet. If you are, the website may be temporarily down. ähnelt.
        /// </summary>
        internal static string ErrorUpdateContentGeneric {
            get {
                return ResourceManager.GetString("ErrorUpdateContentGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode ähnelt.
        /// </summary>
        internal static string FullscreenMode {
            get {
                return ResourceManager.GetString("FullscreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always on top ähnelt.
        /// </summary>
        internal static string FullscreenModeAlwaysOnTop {
            get {
                return ResourceManager.GetString("FullscreenModeAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forces OnTopReplica to stay always on top. ähnelt.
        /// </summary>
        internal static string FullscreenModeAlwaysOnTopTT {
            get {
                return ResourceManager.GetString("FullscreenModeAlwaysOnTopTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click through ähnelt.
        /// </summary>
        internal static string FullscreenModeClickThrough {
            get {
                return ResourceManager.GetString("FullscreenModeClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica will behave like a transparent overlay that lets your clicks through to the windows below. ähnelt.
        /// </summary>
        internal static string FullscreenModeClickThroughTT {
            get {
                return ResourceManager.GetString("FullscreenModeClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Standard ähnelt.
        /// </summary>
        internal static string FullscreenModeNormal {
            get {
                return ResourceManager.GetString("FullscreenModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behaves like an ordinary window. You can bring other windows above OnTopReplica. ähnelt.
        /// </summary>
        internal static string FullscreenModeNormalTT {
            get {
                return ResourceManager.GetString("FullscreenModeNormalTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica fullscreen ähnelt.
        /// </summary>
        internal static string FullscreenTitle {
            get {
                return ResourceManager.GetString("FullscreenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable ähnelt.
        /// </summary>
        internal static string GroupSwitchModeDisableButton {
            get {
                return ResourceManager.GetString("GroupSwitchModeDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Group mode ähnelt.
        /// </summary>
        internal static string GroupSwitchModeEnableButton {
            get {
                return ResourceManager.GetString("GroupSwitchModeEnableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select multiple windows to enable. ähnelt.
        /// </summary>
        internal static string GroupSwitchModeStatusDisabled {
            get {
                return ResourceManager.GetString("GroupSwitchModeStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group switch mode is enabled. ähnelt.
        /// </summary>
        internal static string GroupSwitchModeStatusEnabled {
            get {
                return ResourceManager.GetString("GroupSwitchModeStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group switch mode: ähnelt.
        /// </summary>
        internal static string GroupSwitchModeTitle {
            get {
                return ResourceManager.GetString("GroupSwitchModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows ähnelt.
        /// </summary>
        internal static string GroupSwitchModeWindows {
            get {
                return ResourceManager.GetString("GroupSwitchModeWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Homepage: www.codeplex.com/ontopreplica. ähnelt.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to enable &quot;click forwarding&quot;? ähnelt.
        /// </summary>
        internal static string InfoClickForwarding {
            get {
                return ResourceManager.GetString("InfoClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If this mode is enabled, OnTopReplica will forward all left mouse clicks to the window that is being cloned (this will allow you to do basic mouse operations on the cloned window without having to activate it).
        ///
        ///To exit this mode, push ESC. ähnelt.
        /// </summary>
        internal static string InfoClickForwardingContent {
            get {
                return ResourceManager.GetString("InfoClickForwardingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click forwarding ähnelt.
        /// </summary>
        internal static string InfoClickForwardingTitle {
            get {
                return ResourceManager.GetString("InfoClickForwardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Click-Through mode? ähnelt.
        /// </summary>
        internal static string InfoClickThrough {
            get {
                return ResourceManager.GetString("InfoClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click-through only works if it has been enabled in the Resize submenu and if the window is semi-transparent. ähnelt.
        /// </summary>
        internal static string InfoClickThroughDetails {
            get {
                return ResourceManager.GetString("InfoClickThroughDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In this mode the fullscreen window will behave as a partially transparent overlay, allowing you to click on the other windows behind it.
        ///
        ///To return to normal mode anytime, activate OnTopReplica by clicking on the task bar (or the tray icon). ähnelt.
        /// </summary>
        internal static string InfoClickThroughInformation {
            get {
                return ResourceManager.GetString("InfoClickThroughInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No, thank you.
        ///You can enable click-through later ähnelt.
        /// </summary>
        internal static string InfoClickThroughNo {
            get {
                return ResourceManager.GetString("InfoClickThroughNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Click-Through ähnelt.
        /// </summary>
        internal static string InfoClickThroughOk {
            get {
                return ResourceManager.GetString("InfoClickThroughOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click-Through mode ähnelt.
        /// </summary>
        internal static string InfoClickThroughTitle {
            get {
                return ResourceManager.GetString("InfoClickThroughTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica has been updated. ähnelt.
        /// </summary>
        internal static string InfoUpdated {
            get {
                return ResourceManager.GetString("InfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In order to use the updated version of OnTopReplica you&apos;ll have to restart the application. ähnelt.
        /// </summary>
        internal static string InfoUpdatedContent {
            get {
                return ResourceManager.GetString("InfoUpdatedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update successful ähnelt.
        /// </summary>
        internal static string InfoUpdatedTitle {
            get {
                return ResourceManager.GetString("InfoUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica is up to date. ähnelt.
        /// </summary>
        internal static string InfoUpToDate {
            get {
                return ResourceManager.GetString("InfoUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No update available ähnelt.
        /// </summary>
        internal static string InfoUpToDateTitle {
            get {
                return ResourceManager.GetString("InfoUpToDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About... ähnelt.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hides the main window and displays the &quot;about&quot; box. ähnelt.
        /// </summary>
        internal static string MenuAboutTT {
            get {
                return ResourceManager.GetString("MenuAboutTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        internal static string MenuAdvanced {
            get {
                return ResourceManager.GetString("MenuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show window border ähnelt.
        /// </summary>
        internal static string MenuChrome {
            get {
                return ResourceManager.GetString("MenuChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggles the display of the window border. ähnelt.
        /// </summary>
        internal static string MenuChromeTT {
            get {
                return ResourceManager.GetString("MenuChromeTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Click forwarding ähnelt.
        /// </summary>
        internal static string MenuClickForwarding {
            get {
                return ResourceManager.GetString("MenuClickForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable &quot;click forwarding&quot; to the cloned window. ähnelt.
        /// </summary>
        internal static string MenuClickForwardingTT {
            get {
                return ResourceManager.GetString("MenuClickForwardingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Click-Through ähnelt.
        /// </summary>
        internal static string MenuClickThrough {
            get {
                return ResourceManager.GetString("MenuClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica will behave like a transparent overlay that lets your clicks through to the windows below. ähnelt.
        /// </summary>
        internal static string MenuClickThroughTT {
            get {
                return ResourceManager.GetString("MenuClickThroughTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Closes OnTopReplica. ähnelt.
        /// </summary>
        internal static string MenuCloseTT {
            get {
                return ResourceManager.GetString("MenuCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2:1 Double ähnelt.
        /// </summary>
        internal static string MenuFitDouble {
            get {
                return ResourceManager.GetString("MenuFitDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fullscreen ähnelt.
        /// </summary>
        internal static string MenuFitFullscreen {
            get {
                return ResourceManager.GetString("MenuFitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:2 Half ähnelt.
        /// </summary>
        internal static string MenuFitHalf {
            get {
                return ResourceManager.GetString("MenuFitHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:1 Fit to window ähnelt.
        /// </summary>
        internal static string MenuFitOriginal {
            get {
                return ResourceManager.GetString("MenuFitOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1:4 Quarter ähnelt.
        /// </summary>
        internal static string MenuFitQuarter {
            get {
                return ResourceManager.GetString("MenuFitQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group Switch mode ähnelt.
        /// </summary>
        internal static string MenuGroupSwitch {
            get {
                return ResourceManager.GetString("MenuGroupSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica will automatically clone a window from an user defined group, switching to the one least recently activated to the foreground. ähnelt.
        /// </summary>
        internal static string MenuGroupSwitchTT {
            get {
                return ResourceManager.GetString("MenuGroupSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 100% (opaque) ähnelt.
        /// </summary>
        internal static string MenuOp100 {
            get {
                return ResourceManager.GetString("MenuOp100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets OnTopReplica to be completely opaque. ähnelt.
        /// </summary>
        internal static string MenuOp100TT {
            get {
                return ResourceManager.GetString("MenuOp100TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 25% ähnelt.
        /// </summary>
        internal static string MenuOp25 {
            get {
                return ResourceManager.GetString("MenuOp25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets OnTopReplica to 25% opacity. ähnelt.
        /// </summary>
        internal static string MenuOp25TT {
            get {
                return ResourceManager.GetString("MenuOp25TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 50% ähnelt.
        /// </summary>
        internal static string MenuOp50 {
            get {
                return ResourceManager.GetString("MenuOp50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets OnTopReplica to 50% opacity. ähnelt.
        /// </summary>
        internal static string MenuOp50TT {
            get {
                return ResourceManager.GetString("MenuOp50TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 75% ähnelt.
        /// </summary>
        internal static string MenuOp75 {
            get {
                return ResourceManager.GetString("MenuOp75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sets OnTopReplica to 75% opacity. ähnelt.
        /// </summary>
        internal static string MenuOp75TT {
            get {
                return ResourceManager.GetString("MenuOp75TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opacity ähnelt.
        /// </summary>
        internal static string MenuOpacity {
            get {
                return ResourceManager.GetString("MenuOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays OnTopReplica. ähnelt.
        /// </summary>
        internal static string MenuOpenTT {
            get {
                return ResourceManager.GetString("MenuOpenTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom Left ähnelt.
        /// </summary>
        internal static string MenuPosBottomLeft {
            get {
                return ResourceManager.GetString("MenuPosBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom Right ähnelt.
        /// </summary>
        internal static string MenuPosBottomRight {
            get {
                return ResourceManager.GetString("MenuPosBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Center ähnelt.
        /// </summary>
        internal static string MenuPosCenter {
            get {
                return ResourceManager.GetString("MenuPosCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disabled ähnelt.
        /// </summary>
        internal static string MenuPosDisabled {
            get {
                return ResourceManager.GetString("MenuPosDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position lock ähnelt.
        /// </summary>
        internal static string MenuPosition {
            get {
                return ResourceManager.GetString("MenuPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically position OnTopReplica on the current screen. ähnelt.
        /// </summary>
        internal static string MenuPositionTT {
            get {
                return ResourceManager.GetString("MenuPositionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top Left ähnelt.
        /// </summary>
        internal static string MenuPosTopLeft {
            get {
                return ResourceManager.GetString("MenuPosTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top Right ähnelt.
        /// </summary>
        internal static string MenuPosTopRight {
            get {
                return ResourceManager.GetString("MenuPosTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit fullscreen mode ähnelt.
        /// </summary>
        internal static string MenuQuitFullscreen {
            get {
                return ResourceManager.GetString("MenuQuitFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recall last position and size ähnelt.
        /// </summary>
        internal static string MenuRecall {
            get {
                return ResourceManager.GetString("MenuRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggles whether OnTopReplica should store its last position and size and use them when it is restarted. ähnelt.
        /// </summary>
        internal static string MenuRecallTT {
            get {
                return ResourceManager.GetString("MenuRecallTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize ähnelt.
        /// </summary>
        internal static string MenuReduce {
            get {
                return ResourceManager.GetString("MenuReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimizes OnTopReplica to the task bar (or the tray). ähnelt.
        /// </summary>
        internal static string MenuReduceTT {
            get {
                return ResourceManager.GetString("MenuReduceTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select region... ähnelt.
        /// </summary>
        internal static string MenuRegion {
            get {
                return ResourceManager.GetString("MenuRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switches to &quot;region mode&quot;, that allows you to select a limited region of the source&apos;s window as thumbnail. ähnelt.
        /// </summary>
        internal static string MenuRegionTT {
            get {
                return ResourceManager.GetString("MenuRegionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset window ähnelt.
        /// </summary>
        internal static string MenuReset {
            get {
                return ResourceManager.GetString("MenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resets OnTopReplica settings and its main window. ähnelt.
        /// </summary>
        internal static string MenuResetTT {
            get {
                return ResourceManager.GetString("MenuResetTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize ähnelt.
        /// </summary>
        internal static string MenuResize {
            get {
                return ResourceManager.GetString("MenuResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restore last cloned window ähnelt.
        /// </summary>
        internal static string MenuRestoreLast {
            get {
                return ResourceManager.GetString("MenuRestoreLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die When enabled, OnTopReplica will attempt to restore the last cloned window on start up. ähnelt.
        /// </summary>
        internal static string MenuRestoreLastTT {
            get {
                return ResourceManager.GetString("MenuRestoreLastTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings... ähnelt.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays the settings panel. ähnelt.
        /// </summary>
        internal static string MenuSettingsTT {
            get {
                return ResourceManager.GetString("MenuSettingsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch to window ähnelt.
        /// </summary>
        internal static string MenuSwitch {
            get {
                return ResourceManager.GetString("MenuSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switches to the source window and hides OnTopReplica. ähnelt.
        /// </summary>
        internal static string MenuSwitchTT {
            get {
                return ResourceManager.GetString("MenuSwitchTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select window ähnelt.
        /// </summary>
        internal static string MenuWindows {
            get {
                return ResourceManager.GetString("MenuWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - none - ähnelt.
        /// </summary>
        internal static string MenuWindowsNone {
            get {
                return ResourceManager.GetString("MenuWindowsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays a list of window you can select as thumbnail source. ähnelt.
        /// </summary>
        internal static string MenuWindowsTT {
            get {
                return ResourceManager.GetString("MenuWindowsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - whole - ähnelt.
        /// </summary>
        internal static string MenuWindowsWholeRegion {
            get {
                return ResourceManager.GetString("MenuWindowsWholeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        internal static string RegionsBottom {
            get {
                return ResourceManager.GetString("RegionsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current region: ähnelt.
        /// </summary>
        internal static string RegionsCurrentRegion {
            get {
                return ResourceManager.GetString("RegionsCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string RegionsDeleteButton {
            get {
                return ResourceManager.GetString("RegionsDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string RegionsDoneButton {
            get {
                return ResourceManager.GetString("RegionsDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        internal static string RegionsHeight {
            get {
                return ResourceManager.GetString("RegionsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        internal static string RegionsLeft {
            get {
                return ResourceManager.GetString("RegionsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string RegionsResetButton {
            get {
                return ResourceManager.GetString("RegionsResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right ähnelt.
        /// </summary>
        internal static string RegionsRight {
            get {
                return ResourceManager.GetString("RegionsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string RegionsSaveButton {
            get {
                return ResourceManager.GetString("RegionsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stored regions ähnelt.
        /// </summary>
        internal static string RegionsStoredRegions {
            get {
                return ResourceManager.GetString("RegionsStoredRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regions: ähnelt.
        /// </summary>
        internal static string RegionsTitle {
            get {
                return ResourceManager.GetString("RegionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        internal static string RegionsTop {
            get {
                return ResourceManager.GetString("RegionsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        internal static string RegionsWidth {
            get {
                return ResourceManager.GetString("RegionsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X ähnelt.
        /// </summary>
        internal static string RegionsX {
            get {
                return ResourceManager.GetString("RegionsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y ähnelt.
        /// </summary>
        internal static string RegionsY {
            get {
                return ResourceManager.GetString("RegionsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right-click here to start... ähnelt.
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clone current window ähnelt.
        /// </summary>
        internal static string SettingsHotKeyClone {
            get {
                return ResourceManager.GetString("SettingsHotKeyClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die These system-wide shortcuts can also be used when OnTopReplica is not in focus. ähnelt.
        /// </summary>
        internal static string SettingsHotKeyDescription {
            get {
                return ResourceManager.GetString("SettingsHotKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show/Hide ähnelt.
        /// </summary>
        internal static string SettingsHotKeyShowHide {
            get {
                return ResourceManager.GetString("SettingsHotKeyShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hot keys: ähnelt.
        /// </summary>
        internal static string SettingsHotKeyTitle {
            get {
                return ResourceManager.GetString("SettingsHotKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language: ähnelt.
        /// </summary>
        internal static string SettingsLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Requires a restart. ähnelt.
        /// </summary>
        internal static string SettingsRestartRequired {
            get {
                return ResourceManager.GetString("SettingsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel update
        ///OnTopReplica will prompt you the next time it is started. ähnelt.
        /// </summary>
        internal static string UpdateAvailableCommandCancel {
            get {
                return ResourceManager.GetString("UpdateAvailableCommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download
        ///Install OnTopReplica {0}. ähnelt.
        /// </summary>
        internal static string UpdateAvailableCommandOk {
            get {
                return ResourceManager.GetString("UpdateAvailableCommandOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new version can be downloaded and installed from the official website. ähnelt.
        /// </summary>
        internal static string UpdateAvailableContent {
            get {
                return ResourceManager.GetString("UpdateAvailableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed version: {0}
        ///Available version: {1} ähnelt.
        /// </summary>
        internal static string UpdateAvailableExpanded {
            get {
                return ResourceManager.GetString("UpdateAvailableExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version {0} available ähnelt.
        /// </summary>
        internal static string UpdateAvailableInstruction {
            get {
                return ResourceManager.GetString("UpdateAvailableInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}/{1} bytes downloaded. ähnelt.
        /// </summary>
        internal static string UpdateDownloadingContent {
            get {
                return ResourceManager.GetString("UpdateDownloadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading... ähnelt.
        /// </summary>
        internal static string UpdateDownloadingInstruction {
            get {
                return ResourceManager.GetString("UpdateDownloadingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The latest version of OnTopReplica is already installed. The program automatically checks for updates at every start.
        ///
        ///You can keep up to date about OnTopReplica&apos;s development, suggest improvements and new features by &lt;a href=&quot;website&quot;&gt;visiting the official website&lt;/a&gt;. ähnelt.
        /// </summary>
        internal static string UpdateInfoContent {
            get {
                return ResourceManager.GetString("UpdateInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest stable version released on {0}. ähnelt.
        /// </summary>
        internal static string UpdateInfoFooter {
            get {
                return ResourceManager.GetString("UpdateInfoFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica is up to date ähnelt.
        /// </summary>
        internal static string UpdateInfoInstruction {
            get {
                return ResourceManager.GetString("UpdateInfoInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install
        ///OnTopReplica will be closed and the update installed. ähnelt.
        /// </summary>
        internal static string UpdateReadyCommandOk {
            get {
                return ResourceManager.GetString("UpdateReadyCommandOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica version {0} is ready to be installed on your computer. ähnelt.
        /// </summary>
        internal static string UpdateReadyContent {
            get {
                return ResourceManager.GetString("UpdateReadyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ready ähnelt.
        /// </summary>
        internal static string UpdateReadyInstruction {
            get {
                return ResourceManager.GetString("UpdateReadyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OnTopReplica updates ähnelt.
        /// </summary>
        internal static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
    }
}
